// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(RegistrosContext))]
    partial class RegistrosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Pago", b =>
                {
                    b.Property<string>("IdDePago")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoDePago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorDePago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("personaNumeroDeCocumento")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdDePago");

                    b.HasIndex("personaNumeroDeCocumento");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Entity.Persona", b =>
                {
                    b.Property<string>("NumeroDeCocumento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumeroDeCocumento");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Entity.Pago", b =>
                {
                    b.HasOne("Entity.Persona", "persona")
                        .WithMany("Pago")
                        .HasForeignKey("personaNumeroDeCocumento");
                });
#pragma warning restore 612, 618
        }
    }
}
